name: CI

on:
  pull_request:
    branches:
      - "*.*"
      - master
  push:
    branches:
      - "*.*"
      - master

jobs:
  tests:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
        doctrine-version:
          - '2.20.3'
          - '3.3.3'
        dependencies:
            - 'lowest'
            - 'highest'

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          tools: flex
          php-version: "${{ matrix.php-version }}"
          coverage: none

      - name: "Set Doctrine ORM version"
        run: composer require "doctrine/orm:${{ matrix.doctrine-version }}" --dev --no-update

      - name: "Install dependencies"
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: "Run tests"
        run: composer test

  coding-standard:
    runs-on: ubuntu-24.04
    name: Coding Standard
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          tools: flex
          php-version: "8.2"

      - name: "Install dependencies"
        uses: ramsey/composer-install@v2

      - name: "Check coding standard"
        run: composer check-cs
