name: CI

on:
  pull_request:
    branches:
      - "*.*"
      - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres:17.5
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: database
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.2'
          - '8.3'
          - '8.4'
        dependencies:
            - 'lowest'
            - 'highest'

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          tools: flex
          php-version: "${{ matrix.php-version }}"
          coverage: none

      - name: "Install dependencies"
        uses: ramsey/composer-install@v3
        with:
         dependency-versions: ${{ matrix.dependencies }}

      - name: "Run tests"
        run: composer test

      - name: "Run example"
        run: |
          cd example; composer install; composer test

  coding-standard:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          tools: flex
          php-version: "8.2"

      - name: "Install dependencies"
        uses: ramsey/composer-install@v3

      - name: "Check coding standard"
        run: composer check-cs
